version: '3.8'

services:
  # L2: MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: uam-mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  # L3: In-Memory DB (Priority Queue)
  redis:
    image: redis:7-alpine
    container_name: uam-redis
    ports:
      - "6379:6379"
